/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package airlines;

import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.sql.*;

public class Booking extends javax.swing.JFrame {

    int start_ticket;
    int availEco;
    int availBus;
    int totalEco;
    int totalBus;
    String FlightNo;
    String depTime;
    String arrTime;
    int ecoPrice;
    int busPrice;
    int userID;
    int cost;

    public Booking(String Flightno, String fromiata, String toiata, String deptime, String arrtime, String via, int ecoprice, int busprice, int userid) {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.height) / 2));

        flightNo.setText(Flightno);
        depOn.setText(deptime.substring(0, 10));
        depAt.setText(deptime.substring(11, 16) + " hrs");
        arrOn.setText(arrtime.substring(0, 10));
        arrAt.setText(arrtime.substring(11, 16) + " hrs");
        ecocostINR.setText(ecoprice + " INR");
        buscostINR.setText(busprice + " INR");

        FlightNo = Flightno;
        depTime = deptime;
        arrTime = arrtime;
        ecoPrice = ecoprice;
        busPrice = busprice;
        userID = userid;

        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
            Statement st = con.createStatement();
            Statement st1 = con.createStatement();
            Statement st2 = con.createStatement();
            ResultSet rs4 = st1.executeQuery("select ecoseats,busseats from flight where flightno='" + Flightno + "'");
            rs4.next();
            totalEco = rs4.getInt(1);
            totalBus = rs4.getInt(2);
            ResultSet rs3 = st2.executeQuery("select min(availeco),min(availbus) "
                    + "from particularflight natural join flight  "
                    + "where to_char(depdate,'yyyy-mm-dd hh24:mi')>='" + deptime + "'"
                    + "  and to_char(arrdate,'yyyy-mm-dd hh24:mi')<='" + arrtime + "'"
                    + " group by flightno  "
                    + " having flightno='" + Flightno + "'");
            rs3.next();
            availEco = rs3.getInt(1);
            availBus = rs3.getInt(2);

            ResultSet rs = st.executeQuery("select apname from airport where iatacode='" + fromiata + "'");
            rs.next();
            depAirport.setText(rs.getString(1) + " Airport");

            ResultSet rs1 = st.executeQuery("select apname from airport where iatacode='" + toiata + "'");
            rs1.next();
            arrAirport.setText(rs1.getString(1) + " Airport");

            ResultSet rs2 = st.executeQuery("select ticket_id.nextval from dual");
            rs2.next();
            start_ticket = rs2.getInt(1);
            resetTicketNo();

        } catch (SQLException se) {
            System.out.println(se);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerLabel = new javax.swing.JLabel();
        cardPanel = new javax.swing.JPanel();
        firstPanel = new javax.swing.JPanel();
        heading1Label = new javax.swing.JLabel();
        flightNoLabel = new javax.swing.JLabel();
        flightNo = new javax.swing.JLabel();
        departLabel = new javax.swing.JLabel();
        depAirport = new javax.swing.JLabel();
        dOnLabel = new javax.swing.JLabel();
        dAtLabel = new javax.swing.JLabel();
        depAt = new javax.swing.JLabel();
        depOn = new javax.swing.JLabel();
        arriveLabel = new javax.swing.JLabel();
        arrAirport = new javax.swing.JLabel();
        aOnLabel = new javax.swing.JLabel();
        arrOn = new javax.swing.JLabel();
        aAtLabel = new javax.swing.JLabel();
        arrAt = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        ecocostINR = new javax.swing.JLabel();
        bookButton1 = new javax.swing.JButton();
        backButton1 = new javax.swing.JButton();
        messageLabel = new javax.swing.JLabel();
        buscostINR = new javax.swing.JLabel();
        economyLabel = new javax.swing.JLabel();
        businessLabel = new javax.swing.JLabel();
        secondPanel = new javax.swing.JPanel();
        heading2Label = new javax.swing.JLabel();
        passengerNumLabel = new javax.swing.JLabel();
        passengerScrollPane = new javax.swing.JScrollPane();
        passengerTable = new javax.swing.JTable();
        nextButton2 = new javax.swing.JButton();
        cancelButton2 = new javax.swing.JButton();
        backButton2 = new javax.swing.JButton();
        passengerNum = new com.toedter.components.JSpinField();
        seatingClass = new javax.swing.JComboBox();
        messageLabel1 = new javax.swing.JLabel();
        thirdPanel = new javax.swing.JPanel();
        heading3Label = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cityLabel = new javax.swing.JLabel();
        countryLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        regionLabel = new javax.swing.JLabel();
        region = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        addressScrollPane = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        nextButton3 = new javax.swing.JButton();
        cancelButton3 = new javax.swing.JButton();
        backButton3 = new javax.swing.JButton();
        fourthPanel = new javax.swing.JPanel();
        heading4Label = new javax.swing.JLabel();
        flightNoLabel4 = new javax.swing.JLabel();
        flightNo4 = new javax.swing.JLabel();
        depTime4 = new javax.swing.JLabel();
        depTimeLabel4 = new javax.swing.JLabel();
        confirmationScrollPane3 = new javax.swing.JScrollPane();
        confirmationTable = new javax.swing.JTable();
        totalCostLabel4 = new javax.swing.JLabel();
        totalCost4 = new javax.swing.JLabel();
        bookNowButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        cancelButton4 = new javax.swing.JButton();
        BackgroundIMG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Book your ticket!");
        setPreferredSize(new java.awt.Dimension(700, 445));
        getContentPane().setLayout(null);

        mainPanel.setOpaque(false);

        headerLabel.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        headerLabel.setText("Book your tickets in 4 easy steps!");

        cardPanel.setOpaque(false);
        cardPanel.setPreferredSize(new java.awt.Dimension(469, 285));
        cardPanel.setLayout(new java.awt.CardLayout());

        firstPanel.setOpaque(false);

        heading1Label.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        heading1Label.setText("Verify Flight Detials...");

        flightNoLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        flightNoLabel.setText("Flight No: ");

        flightNo.setFont(new java.awt.Font("Andalus", 0, 14)); // NOI18N
        flightNo.setText("AI466");

        departLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        departLabel.setText("Departs From");

        depAirport.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        depAirport.setText("Lokpriya Gopinath Bordoloi International Airport");

        dOnLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        dOnLabel.setText("On");

        dAtLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        dAtLabel.setText("At");

        depAt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        depAt.setText("13:22 hrs");

        depOn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        depOn.setText("26-Nov-2013");

        arriveLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        arriveLabel.setText("Arrives At");

        arrAirport.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arrAirport.setText("Lokpriya Gopinath Bordoloi International Airport");

        aOnLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        aOnLabel.setText("On");

        arrOn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arrOn.setText("27-Nov-2013");

        aAtLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        aAtLabel.setText("At");

        arrAt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        arrAt.setText("13:22 hrs");

        costLabel.setFont(new java.awt.Font("Agency FB", 1, 16)); // NOI18N
        costLabel.setText("Cost Per Person: ");

        ecocostINR.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        ecocostINR.setText("32,000 INR");

        bookButton1.setText("Book >>");
        bookButton1.setOpaque(false);
        bookButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButton1ActionPerformed(evt);
            }
        });

        backButton1.setText("<< Back");
        backButton1.setOpaque(false);
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        messageLabel.setText("Not the flight you were looking for?");

        buscostINR.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        buscostINR.setText("32,000 INR");

        economyLabel.setText("Economy");

        businessLabel.setText("Business");

        javax.swing.GroupLayout firstPanelLayout = new javax.swing.GroupLayout(firstPanel);
        firstPanel.setLayout(firstPanelLayout);
        firstPanelLayout.setHorizontalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depAirport)
                            .addComponent(arriveLabel)
                            .addComponent(arrAirport)
                            .addComponent(departLabel)
                            .addGroup(firstPanelLayout.createSequentialGroup()
                                .addComponent(flightNoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(flightNo)
                                .addGap(20, 20, 20)
                                .addComponent(costLabel)))
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(firstPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dOnLabel)
                                    .addComponent(aOnLabel)
                                    .addComponent(depOn)
                                    .addComponent(arrOn)))
                            .addGroup(firstPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(economyLabel)
                                    .addComponent(ecocostINR)))))
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading1Label)))
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dAtLabel)
                            .addComponent(depAt)
                            .addComponent(aAtLabel)
                            .addComponent(arrAt))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(businessLabel)
                            .addComponent(buscostINR))
                        .addContainerGap())))
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(messageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookButton1)
                .addContainerGap())
        );
        firstPanelLayout.setVerticalGroup(
            firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(firstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(firstPanelLayout.createSequentialGroup()
                            .addComponent(heading1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                            .addComponent(economyLabel)
                            .addGap(7, 7, 7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, firstPanelLayout.createSequentialGroup()
                        .addComponent(businessLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNoLabel)
                    .addComponent(flightNo)
                    .addComponent(costLabel)
                    .addComponent(ecocostINR)
                    .addComponent(buscostINR))
                .addGap(18, 18, 18)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dOnLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(departLabel)
                        .addComponent(dAtLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depAirport)
                    .addComponent(depAt)
                    .addComponent(depOn))
                .addGap(18, 18, 18)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arriveLabel)
                    .addComponent(aOnLabel)
                    .addComponent(aAtLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrAirport)
                    .addComponent(arrOn)
                    .addComponent(arrAt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(firstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookButton1)
                    .addComponent(backButton1)
                    .addComponent(messageLabel))
                .addContainerGap())
        );

        cardPanel.add(firstPanel, "card1");

        secondPanel.setOpaque(false);
        secondPanel.setPreferredSize(new java.awt.Dimension(469, 285));

        heading2Label.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        heading2Label.setText("Passenger Information");

        passengerNumLabel.setText("No.of passengers");

        passengerScrollPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        passengerScrollPane.setOpaque(false);

        passengerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "First Name", "Last Name", "DOB(dd-mm-yyyy)", "Citizenship", "Meal Option"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        passengerTable.setOpaque(false);
        passengerTable.getTableHeader().setReorderingAllowed(false);
        passengerScrollPane.setViewportView(passengerTable);
        if (passengerTable.getColumnModel().getColumnCount() > 0) {
            passengerTable.getColumnModel().getColumn(0).setResizable(false);
            passengerTable.getColumnModel().getColumn(0).setPreferredWidth(21);
            passengerTable.getColumnModel().getColumn(1).setResizable(false);
            passengerTable.getColumnModel().getColumn(1).setPreferredWidth(70);
            passengerTable.getColumnModel().getColumn(2).setResizable(false);
            passengerTable.getColumnModel().getColumn(2).setPreferredWidth(70);
            passengerTable.getColumnModel().getColumn(3).setResizable(false);
            passengerTable.getColumnModel().getColumn(3).setPreferredWidth(95);
            passengerTable.getColumnModel().getColumn(4).setResizable(false);
            passengerTable.getColumnModel().getColumn(4).setPreferredWidth(70);
            passengerTable.getColumnModel().getColumn(5).setResizable(false);
            passengerTable.getColumnModel().getColumn(5).setPreferredWidth(60);
        }

        nextButton2.setText("Next >>");
        nextButton2.setOpaque(false);
        nextButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton2ActionPerformed(evt);
            }
        });

        cancelButton2.setText("Cancel");
        cancelButton2.setOpaque(false);
        cancelButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton2ActionPerformed(evt);
            }
        });

        backButton2.setText("<< Back");
        backButton2.setOpaque(false);
        backButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton2ActionPerformed(evt);
            }
        });

        passengerNum.setDoubleBuffered(false);
        passengerNum.setMaximum(9);
        passengerNum.setMinimum(1);
        passengerNum.setOpaque(false);
        passengerNum.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                passengerNumPropertyChange(evt);
            }
        });

        seatingClass.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Economy Class", "Business Class" }));
        seatingClass.setOpaque(false);

        messageLabel1.setVisible(false);
        messageLabel1.setText("Enter all details!");

        javax.swing.GroupLayout secondPanelLayout = new javax.swing.GroupLayout(secondPanel);
        secondPanel.setLayout(secondPanelLayout);
        secondPanelLayout.setHorizontalGroup(
            secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPanelLayout.createSequentialGroup()
                .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading2Label)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondPanelLayout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passengerScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, secondPanelLayout.createSequentialGroup()
                                .addComponent(messageLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(backButton2)
                                .addGap(6, 6, 6)
                                .addComponent(cancelButton2)
                                .addGap(6, 6, 6)
                                .addComponent(nextButton2)))))
                .addContainerGap())
            .addGroup(secondPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(passengerNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passengerNum, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seatingClass, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        secondPanelLayout.setVerticalGroup(
            secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(secondPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading2Label)
                .addGap(18, 18, 18)
                .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(secondPanelLayout.createSequentialGroup()
                        .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passengerNumLabel)
                            .addComponent(passengerNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(passengerScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(secondPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nextButton2)
                            .addComponent(cancelButton2)
                            .addComponent(backButton2)
                            .addComponent(messageLabel1)))
                    .addGroup(secondPanelLayout.createSequentialGroup()
                        .addComponent(seatingClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        cardPanel.add(secondPanel, "card2");

        thirdPanel.setOpaque(false);
        thirdPanel.setPreferredSize(new java.awt.Dimension(469, 285));

        heading3Label.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        heading3Label.setText("Passenger Information");

        phoneLabel.setText("Phone: ");

        addressLabel.setText("Address: ");

        cityLabel.setText("City: ");

        countryLabel.setText("Country: ");

        emailLabel.setText("e-mail:");

        regionLabel.setText("Region: ");

        region.setOpaque(false);

        country.setOpaque(false);

        city.setOpaque(false);

        email.setOpaque(false);

        phone.setOpaque(false);

        addressScrollPane.setOpaque(false);

        address.setColumns(20);
        address.setRows(5);
        address.setOpaque(false);
        addressScrollPane.setViewportView(address);

        nextButton3.setText("Next >>");
        nextButton3.setOpaque(false);
        nextButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextButton3ActionPerformed(evt);
            }
        });

        cancelButton3.setText("Cancel");
        cancelButton3.setOpaque(false);
        cancelButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton3ActionPerformed(evt);
            }
        });

        backButton3.setText("<< Back");
        backButton3.setOpaque(false);
        backButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout thirdPanelLayout = new javax.swing.GroupLayout(thirdPanel);
        thirdPanel.setLayout(thirdPanelLayout);
        thirdPanelLayout.setHorizontalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdPanelLayout.createSequentialGroup()
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(thirdPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(heading3Label))
                    .addGroup(thirdPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(thirdPanelLayout.createSequentialGroup()
                                .addComponent(addressLabel)
                                .addGap(9, 9, 9)
                                .addComponent(addressScrollPane))
                            .addGroup(thirdPanelLayout.createSequentialGroup()
                                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(thirdPanelLayout.createSequentialGroup()
                                        .addComponent(countryLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(country))
                                    .addGroup(thirdPanelLayout.createSequentialGroup()
                                        .addComponent(phoneLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(thirdPanelLayout.createSequentialGroup()
                                        .addComponent(cityLabel)
                                        .addGap(29, 29, 29)
                                        .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(thirdPanelLayout.createSequentialGroup()
                                        .addComponent(regionLabel)
                                        .addGap(10, 10, 10)
                                        .addComponent(region))
                                    .addGroup(thirdPanelLayout.createSequentialGroup()
                                        .addComponent(emailLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, thirdPanelLayout.createSequentialGroup()
                                .addComponent(backButton3)
                                .addGap(6, 6, 6)
                                .addComponent(cancelButton3)
                                .addGap(6, 6, 6)
                                .addComponent(nextButton3)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        thirdPanelLayout.setVerticalGroup(
            thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(thirdPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading3Label)
                .addGap(18, 18, 18)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneLabel)
                    .addComponent(emailLabel)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addressLabel)
                    .addComponent(addressScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityLabel)
                    .addComponent(regionLabel)
                    .addComponent(region, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryLabel)
                    .addComponent(country, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(thirdPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nextButton3)
                    .addComponent(cancelButton3)
                    .addComponent(backButton3))
                .addContainerGap())
        );

        cardPanel.add(thirdPanel, "card3");

        fourthPanel.setMaximumSize(new java.awt.Dimension(469, 285));
        fourthPanel.setMinimumSize(new java.awt.Dimension(469, 285));
        fourthPanel.setOpaque(false);
        fourthPanel.setPreferredSize(new java.awt.Dimension(469, 285));

        heading4Label.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        heading4Label.setText("Ticket Detials");

        flightNoLabel4.setText("Flight No: ");

        flightNo4.setText("AI466");

        depTime4.setText("2013-11-25 03:25:00 hrs");

        depTimeLabel4.setText("Departure time:");

        confirmationScrollPane3.setOpaque(false);

        confirmationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No.", "Ticket No", "Name", "Seat No"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        confirmationTable.setMaximumSize(new java.awt.Dimension(300, 64));
        confirmationTable.setOpaque(false);
        confirmationScrollPane3.setViewportView(confirmationTable);
        if (confirmationTable.getColumnModel().getColumnCount() > 0) {
            confirmationTable.getColumnModel().getColumn(0).setResizable(false);
            confirmationTable.getColumnModel().getColumn(0).setPreferredWidth(21);
            confirmationTable.getColumnModel().getColumn(1).setResizable(false);
            confirmationTable.getColumnModel().getColumn(1).setPreferredWidth(60);
            confirmationTable.getColumnModel().getColumn(2).setResizable(false);
            confirmationTable.getColumnModel().getColumn(2).setPreferredWidth(180);
            confirmationTable.getColumnModel().getColumn(3).setResizable(false);
            confirmationTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }

        totalCostLabel4.setText("Total Cost: ");

        totalCost4.setText("3,20,000 INR");

        bookNowButton.setText("Book Now!");
        bookNowButton.setOpaque(false);
        bookNowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookNowButtonActionPerformed(evt);
            }
        });

        backButton4.setText("<< Back");
        backButton4.setOpaque(false);
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });

        cancelButton4.setText("Cancel");
        cancelButton4.setOpaque(false);
        cancelButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fourthPanelLayout = new javax.swing.GroupLayout(fourthPanel);
        fourthPanel.setLayout(fourthPanelLayout);
        fourthPanelLayout.setHorizontalGroup(
            fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fourthPanelLayout.createSequentialGroup()
                        .addGroup(fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fourthPanelLayout.createSequentialGroup()
                                .addComponent(flightNoLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(flightNo4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(depTimeLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(depTime4))
                            .addGroup(fourthPanelLayout.createSequentialGroup()
                                .addComponent(heading4Label)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fourthPanelLayout.createSequentialGroup()
                        .addComponent(confirmationScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(fourthPanelLayout.createSequentialGroup()
                        .addComponent(totalCostLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(totalCost4)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fourthPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookNowButton)
                .addContainerGap())
        );
        fourthPanelLayout.setVerticalGroup(
            fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(heading4Label)
                .addGap(18, 18, 18)
                .addGroup(fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightNoLabel4)
                    .addComponent(flightNo4)
                    .addComponent(depTime4)
                    .addComponent(depTimeLabel4))
                .addGap(18, 18, 18)
                .addComponent(confirmationScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalCostLabel4)
                    .addComponent(totalCost4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(fourthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookNowButton)
                    .addComponent(backButton4)
                    .addComponent(cancelButton4))
                .addContainerGap())
        );

        cardPanel.add(fourthPanel, "card4");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(headerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(123, Short.MAX_VALUE)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(headerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel);
        mainPanel.setBounds(0, 0, 602, 345);

        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg1.jpg"))); // NOI18N
        getContentPane().add(BackgroundIMG);
        BackgroundIMG.setBounds(0, 0, 690, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bookButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButton1ActionPerformed
        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg2.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card2");
    }//GEN-LAST:event_bookButton1ActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        resetTicketNo();
        dispose();
    }//GEN-LAST:event_backButton1ActionPerformed

    private void backButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton2ActionPerformed

        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg1.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card1");
    }//GEN-LAST:event_backButton2ActionPerformed

    private void cancelButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton2ActionPerformed

        String message = "Are you sure you want cancel your booking? ";

        int reply = javax.swing.JOptionPane.showConfirmDialog(this, message, "Warning", javax.swing.JOptionPane.YES_NO_OPTION);
        if (reply == javax.swing.JOptionPane.YES_OPTION) {
            resetTicketNo();
            dispose();
        }
    }//GEN-LAST:event_cancelButton2ActionPerformed

    private void nextButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton2ActionPerformed
        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg3.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card3");
    }//GEN-LAST:event_nextButton2ActionPerformed

    private void backButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton3ActionPerformed
        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg2.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card2");
    }//GEN-LAST:event_backButton3ActionPerformed

    private void cancelButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton3ActionPerformed
        String message = "Are you sure you want cancel your booking? ";

        int reply = javax.swing.JOptionPane.showConfirmDialog(this, message, "Warning", javax.swing.JOptionPane.YES_NO_OPTION);
        if (reply == javax.swing.JOptionPane.YES_OPTION) {
            resetTicketNo();
            dispose();
        }
    }//GEN-LAST:event_cancelButton3ActionPerformed

    private void nextButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextButton3ActionPerformed
        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg4.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card4");

        resetTicketNo();
        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
            Statement st1 = con.createStatement();
            int seatno;

            if (seatingClass.getSelectedIndex() == 0) {
                cost = passengerNum.getValue() * ecoPrice;
                seatno = totalEco - availEco + 1;
            } else {
                cost = passengerNum.getValue() * busPrice;
                seatno = totalBus - availBus + 1;
            }

            for (int i = 0; i < passengerNum.getValue(); i++) {

                ResultSet rs1 = st1.executeQuery("select ticket_id.nextval from dual");
                rs1.next();
                confirmationTable.getModel().setValueAt(rs1.getInt(1), i, 1);
                String name = passengerTable.getModel().getValueAt(i, 1) + " " + passengerTable.getModel().getValueAt(i, 2);
                confirmationTable.getModel().setValueAt(name, i, 2);
                confirmationTable.getModel().setValueAt(seatno, i, 3);
                seatno++;
            }
            flightNo4.setText(FlightNo);
            depTime4.setText(depTime + " hrs");

            totalCost4.setText(cost + " INR");

        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_nextButton3ActionPerformed

    private void resetTicketNo() {
        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
            Statement st2 = con.createStatement();
            st2.executeQuery("drop sequence ticket_id");
            st2.executeQuery("create sequence ticket_id start with " + start_ticket + " increment by 1");
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        BackgroundIMG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/airlines/bookbg3.jpg")));
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) (cardPanel.getLayout());
        cardLayout.show(cardPanel, "card3");
    }//GEN-LAST:event_backButton4ActionPerformed

    private void cancelButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButton4ActionPerformed
        String message = "Are you sure you want cancel your booking? ";

        int reply = javax.swing.JOptionPane.showConfirmDialog(this, message, "Warning", javax.swing.JOptionPane.YES_NO_OPTION);
        if (reply == javax.swing.JOptionPane.YES_OPTION) {
            resetTicketNo();
            dispose();
        }
    }//GEN-LAST:event_cancelButton4ActionPerformed

    private void passengerNumPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_passengerNumPropertyChange

        javax.swing.table.DefaultTableModel dm1 = (javax.swing.table.DefaultTableModel) passengerTable.getModel();
        javax.swing.table.DefaultTableModel dm2 = (javax.swing.table.DefaultTableModel) confirmationTable.getModel();
        int i = passengerNum.getValue();

        dm1.setRowCount(i);
        dm2.setRowCount(i);

        if (i != 0) {
            confirmationTable.getModel().setValueAt(i, i - 1, 0);
            passengerTable.getModel().setValueAt(i, i - 1, 0);
            passengerTable.getModel().setValueAt(false, i - 1, 5);
        }




    }//GEN-LAST:event_passengerNumPropertyChange

    private void bookNowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookNowButtonActionPerformed
        try {
            Connection con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "system", "oracle");
            Statement st1 = con.createStatement();
            String emailid = email.getText();
            String phoneno = phone.getText();
            String Address = address.getText();
            String City = city.getText();
            String Region = region.getText();
            String Country = country.getText();

            Statement st2 = con.createStatement();
            ResultSet rs2 = st2.executeQuery("select transid.nextval from dual");
            rs2.next();
            int transID = rs2.getInt(1);

            rs2 = st2.executeQuery("select sysdate from dual");
            rs2.next();
            String bookDate = (String) rs2.getString(1);

            Statement st3 = con.createStatement();
            ResultSet rs3 = st3.executeQuery("select fid from particularflight natural join flight where flightno='" + FlightNo
                    + "' and to_char(depdate,'yyyy-mm-dd hh24:mi')='" + depTime + "'");
            rs3.next();
            String DFID = rs3.getString(1);

            rs3 = st3.executeQuery("select fid from particularflight natural join flight where flightno='" + FlightNo
                    + "' and to_char(arrdate,'yyyy-mm-dd hh24:mi')='" + arrTime + "'");
            rs3.next();
            String AFID = rs3.getString(1);

            for (int i = 0; i < passengerNum.getValue(); i++) {

                String fName = (String) passengerTable.getModel().getValueAt(i, 1);
                String lName = (String) passengerTable.getModel().getValueAt(i, 2);
                String DOB = (String) passengerTable.getModel().getValueAt(i, 3);
                String citizenship = (String) passengerTable.getModel().getValueAt(i, 4);

                int mealoption;
                if ((Boolean) passengerTable.getModel().getValueAt(i, 5)) {
                    mealoption = 1;
                } else {
                    mealoption = 0;
                }

                st1.executeUpdate("insert into passenger values(pass_id.nextval,'"
                        + fName + "','" + lName + "','" + emailid + "','" + phoneno + "','"
                        + Address + "','" + City + "','" + Region + "','" + Country + "','"
                        + citizenship + "',to_date('" + DOB + "','dd-mm-yyyy')," + mealoption + ")");

                int ticketno = (int) confirmationTable.getModel().getValueAt(i, 1);
                int seatno = (int) confirmationTable.getModel().getValueAt(i, 3);
                String seatNo = "" + seatno;

                st1.executeUpdate("insert into ticket values(" + ticketno + ","
                        + transID + ",pass_id.currval,'"
                        + seatNo + "'," + cost / passengerNum.getValue()
                        + ",to_date('" + bookDate.substring(0, 10) + "','yyyy-mm-dd'),"
                        + "to_date('" + depTime + "','yyyy-mm-dd hh24:mi'),"
                        + DFID + "," + AFID + ","
                        + "to_date('" + arrTime + "','yyyy-mm-dd hh24:mi')," + seatingClass.getSelectedIndex() + " )");
                        /* st1.executeUpdate("insert into ticket values(" + ticketno + ","
                         + transID + ",pass_id.currval," + DFID + "," + AFID + ",'" + seatNo + "'," + cost / passengerNum.getValue()
                         + ",to_date('" + bookDate.substring(0, 10) + "','yyyy-mm-dd'),to_date('" + depTime + "','yyyy-mm-dd hh24:mi'),"
                         + "to_date('" + arrTime + "','yyyy-mm-dd hh24:mi'))" );  */


                st1.executeUpdate("insert into userticket values(" + userID + "," + ticketno + ")");

            }

            Statement st4 = con.createStatement();
            if (seatingClass.getSelectedIndex() == 0) {
                st4.executeUpdate("update particularflight"
                        + " set availeco=availeco-" + passengerNum.getValue()
                        + " where fid in (select fid from flight where Flightno='" + FlightNo + "')"
                        + "  and to_char(depdate,'yyyy-mm-dd hh24:mi')>='" + depTime + "'"
                        + "  and to_char(arrdate,'yyyy-mm-dd hh24:mi')<='" + arrTime + "'");
            } else {
                st4.executeUpdate("update particularflight"
                        + " set availbus=availbus-" + passengerNum.getValue()
                        + " where fid in (select fid from flight where Flightno='" + FlightNo + "')"
                        + "  and to_char(depdate,'yyyy-mm-dd hh24:mi')>='" + depTime + "'"
                        + "  and to_char(arrdate,'yyyy-mm-dd hh24:mi')<='" + arrTime + "'");
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Booking Successful!");
            this.dispose();
            //FindButtonActionPerformed(evt);
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_bookNowButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackgroundIMG;
    private javax.swing.JLabel aAtLabel;
    private javax.swing.JLabel aOnLabel;
    private javax.swing.JTextArea address;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JScrollPane addressScrollPane;
    private javax.swing.JLabel arrAirport;
    private javax.swing.JLabel arrAt;
    private javax.swing.JLabel arrOn;
    private javax.swing.JLabel arriveLabel;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton backButton2;
    private javax.swing.JButton backButton3;
    private javax.swing.JButton backButton4;
    private javax.swing.JButton bookButton1;
    private javax.swing.JButton bookNowButton;
    private javax.swing.JLabel buscostINR;
    private javax.swing.JLabel businessLabel;
    private javax.swing.JButton cancelButton2;
    private javax.swing.JButton cancelButton3;
    private javax.swing.JButton cancelButton4;
    private javax.swing.JPanel cardPanel;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JScrollPane confirmationScrollPane3;
    private javax.swing.JTable confirmationTable;
    private javax.swing.JLabel costLabel;
    private javax.swing.JTextField country;
    private javax.swing.JLabel countryLabel;
    private javax.swing.JLabel dAtLabel;
    private javax.swing.JLabel dOnLabel;
    private javax.swing.JLabel depAirport;
    private javax.swing.JLabel depAt;
    private javax.swing.JLabel depOn;
    private javax.swing.JLabel depTime4;
    private javax.swing.JLabel depTimeLabel4;
    private javax.swing.JLabel departLabel;
    private javax.swing.JLabel ecocostINR;
    private javax.swing.JLabel economyLabel;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel firstPanel;
    private javax.swing.JLabel flightNo;
    private javax.swing.JLabel flightNo4;
    private javax.swing.JLabel flightNoLabel;
    private javax.swing.JLabel flightNoLabel4;
    private javax.swing.JPanel fourthPanel;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JLabel heading1Label;
    private javax.swing.JLabel heading2Label;
    private javax.swing.JLabel heading3Label;
    private javax.swing.JLabel heading4Label;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel messageLabel;
    private javax.swing.JLabel messageLabel1;
    private javax.swing.JButton nextButton2;
    private javax.swing.JButton nextButton3;
    private com.toedter.components.JSpinField passengerNum;
    private javax.swing.JLabel passengerNumLabel;
    private javax.swing.JScrollPane passengerScrollPane;
    private javax.swing.JTable passengerTable;
    private javax.swing.JTextField phone;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextField region;
    private javax.swing.JLabel regionLabel;
    private javax.swing.JComboBox seatingClass;
    private javax.swing.JPanel secondPanel;
    private javax.swing.JPanel thirdPanel;
    private javax.swing.JLabel totalCost4;
    private javax.swing.JLabel totalCostLabel4;
    // End of variables declaration//GEN-END:variables
}
